import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const aiEnabled = !!process.env.OPENAI_API_KEY;
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar + container */}
        <div className="site-wrapper">
          <Navbar />
          {!aiEnabled && (
            <div
              className="card"
              style={{
                margin: "16px auto 0",
                maxWidth: 960,
                border: "1px solid rgba(239,68,68,0.5)",
                background: "rgba(239,68,68,0.06)",
              }}
            >
              <div className="font-medium">AI grading disabled</div>
              <div className="small muted">
                Set <code>OPENAI_API_KEY</code> to enable AI grading and resume
                matching.
              </div>
            </div>
          )}
          { }
          <main className="site-container">{children}</main>
        </div>
      </body>
    </html>
  );
}
